name: circle_indicator
description: Small library that builds a circle indicator for the PageViewer that can be used on Android and iOS apps.
version: 0.0.7
homepage: https://www.long1.eu
author: long1eu <home@long1.eu>

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

#dependencies:
#  path: ^1.4.1
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
      sdk: flutter

